### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 5

### ISSUE THREAD

**Issue by hamiltino** [openmarket/openmarket#1]
java -jar openmarket.jar -testnet -join 104.236.98.130:4570
13:49:42.089 [main] INFO  com.openmarket.tools.Tools - go version go1

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.String.substring(String.java:1951)
	at com.openmarket.tools.Tools.isGoInstalled(Tools.java:1110)
	at com.openmarket.tools.Tools.ensureGoInstalled(Tools.java:1130)
	at com.openmarket.Main.doMain(Main.java:74)
	at com.openmarket.Main.main(Main.java:101)

**Comment by hamiltino** [comment]
wrong go version installed.

**Comment by tchoulihan** [comment]
Oops, bad on my part there, but also this needs at least go 1.4. It won't
work with go1.
